# Generated by Django 3.1.1 on 2020-09-30 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 18, 10, 50, 427668, tzinfo=utc)),
        ),
    ]
